### PR TITLE
implement Usearch to speed up literature search

### LINKED ISSUE #32: improve search tool performance

### PR DESCRIPTION
**Pull request by vestalisvirginis**
closes #32

### CODE REVIEW

**Comment by boratyng** [comment]
`paperscraper` is missing from requirements.

I am also getting this error:
```
  File "/home/ec2-user/mlxai-2024-team-saddler/app/agents/tp_tools/search.py", line 23, in paper_scraper
    return paperscraper.search_papers(search, pdir=pdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'paperscraper' has no attribute 'search_papers'
```
Did I install a wrong `paperscraper`?

**Comment by combspk** [comment]
> `paperscraper` is missing from requirements.
> 
> I am also getting this error:
> 
> ```
>   File "/home/ec2-user/mlxai-2024-team-saddler/app/agents/tp_tools/search.py", line 23, in paper_scraper
>     return paperscraper.search_papers(search, pdir=pdir)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'paperscraper' has no attribute 'search_papers'
> ```
> 
> Did I install a wrong `paperscraper`?

I had the same issue - you want to use this package: https://github.com/blackadad/paper-scraper

**Comment by vestalisvirginis** [comment]
For installation: 
pip install git+https://github.com/blackadad/paper-scraper.git

**Comment by boratyng** [comment]
Right, I forgot this one is from git. Thanks guys! It is working now. Great!

**Review by boratyng — APPROVED** [review]

**Pull request merged**
